module.exports = [
  { name: "salon 1" },
  { name: "salon 2" },
  { name: "salon 3" },
  { name: "salon 4" },
  { name: "salon 1" },
  { name: "salon 2" },
  { name: "salon 3" },
  { name: "salon 4" },
  { name: "salon 1" },
  { name: "salon 2" },
  { name: "salon 3" },
  { name: "salon 4" },
  { name: "salon 1" },
  { name: "salon 2" },
  { name: "salon 3" },
  { name: "salon 4" },
  { name: "salon 1" },
  { name: "salon 2" },
  { name: "salon 3" },
  { name: "salon 4" },
  { name: "salon 1" },
  { name: "salon 2" },
  { name: "salon 3" }
];
